### ISSUE TITLE
Active line background doesn't work with a dark theme

### ISSUE THREAD

**Issue by Wieke** [j6t/kdbg#13]
Hi

Found a small bug. The background colour of the active light in the text editor seems to be set to a rather light color which doesn't really work with dark themes. In a dark theme the text itself is already quite light which combined with a light highlighting colour makes the entire active line unreadable.

Cheers,

Wieke

**Comment by j6t** [comment]
Do you have an idea how to fix it? Can you suggest a color to is better suited?

**Comment by Wieke** [comment]
So I played with the code a bit and figured out a way to determine the lightness of the foreground text and use it to determine if the highlight color should be light or dark. I changed `SourceWindow::cursorChanged` to this:

```cpp
void SourceWindow::cursorChanged()
{
	QList<QTextEdit::ExtraSelection> extraSelections;
	QTextEdit::ExtraSelection selection;

	QPalette p = this->palette();
	QColor c = p.color(QPalette::Text);

	if (c.lightness() < 100) { // Breeze light 24, Breeze dark 240
		selection.format.setBackground(QColor("#E7E7E7"));
	}
	else {
		selection.format.setBackground(QColor("#191919"));
	}
	selection.format.setProperty(QTextFormat::FullWidthSelection, true);
	selection.cursor = textCursor();
	selection.cursor.clearSelection();
	extraSelections.append(selection);
	setExtraSelections(extraSelections);
}
```

It seems to work, though it's a quick hack, I'm sure there are considerations I missed. And I don't know how well this works with other themes, I only tried with breeze dark & breeze light, maybe the required lightness before switching to a darker highlight needs to be higher. But it is a way to determine how light the text being displayed is which should be a reasonable indicator how light the highlight ought to be.

**Comment by j6t** [comment]
Thanks for the prototype. I'll see what I can do.

**Comment by j6t** [comment]
I've used your code and suggested colors. Thanks!
