### ISSUE TITLE
cmake . fails on Kubuntu

### ISSUE THREAD

**Issue by arnholm** [j6t/kdbg#14]
Hi, I am trying to build kdbg (I want to customise it) under Ubuntu 18.04.3 LTS
 and have followed the build procedure, i.e.

	cmake .
	make
	sudo make install_

However, this fails in the cmake step and I have been unable to figure out what to do to fix the problem (not very familiar with cmake or qt, thow comfortable in C++). This is what I see when I run cmake:

	$ cmake . 
	-- The C compiler identification is GNU 7.4.0
	-- The CXX compiler identification is GNU 7.4.0
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	CMake Error at pics/CMakeLists.txt:1 (include):
	  include could not find load file:

		 ECMInstallIcons

	CMake Error at pics/CMakeLists.txt:33 (ecm_install_icons):
	Unknown CMake command "ecm_install_icons".

What is missing to allow cmake to succeed? I have searched and tried various hints from the web, but all attempts ended in failure.

Thanks.

**Comment by j6t** [comment]
I'm on openSUSE, and I have the file `/usr/share/ECM/modules/ECMInstallIcons.cmake`, which is in package `extra-cmake-modules-5.45.0-lp150.1.1.x86_64`. Look for a corresponding package of your distro.

**Comment by arnholm** [comment]
Many thanks for the reply. I first checked the folder you mention, and the same files are there. I also had extra-cmake-modules isnalled so that was not the problem. After more searching and errors I found I probably was missing "KF5" and found this page https://community.kde.org/Kdenlive/Development/KF5

On that page it recommended to install (for Ubuntu)

sudo apt-get install \
 libkf5archive-dev libkf5bookmarks-dev libkf5coreaddons-dev libkf5config-dev \
 libkf5configwidgets-dev libkf5dbusaddons-dev libkf5kio-dev libkf5widgetsaddons-dev \
 libkf5notifyconfig-dev libkf5newstuff-dev libkf5xmlgui-dev libkf5declarative-dev \
 libkf5notifications-dev libkf5guiaddons-dev libkf5textwidgets-dev libkf5iconthemes-dev \
 kdoctools-dev libkf5crash-dev libkf5filemetadata-dev extra-cmake-modules \
 libsm-dev cmake qtdeclarative5-dev kde-runtime kinit  kio \
 qml-module-qtquick-controls

So I simply tried that, and after doing that I am able to run the kdbg cmake script without errors, and also build kdbg afterwards. So probably there is some undeclared dependency that is resolved by this, but I am not sure which ones in the list above are the minimum required.

**Comment by j6t** [comment]
Thank you very much!

**Comment by arnholm** [comment]
You are welcome. I see you closed this topic, but the build is not quite correct yet. It seems to run, but there are no colored icons for breakpoints or for the main window, so something is missing in the build still. Any ideas?

**Comment by j6t** [comment]
`make install` perhaps? Have a look at your `.config/kdbgrc` that it does not carry a bogus layout. Look for entry `State` in section `MainWindow`; move it out of the way, just in case.
