### ISSUE TITLE
NOPs

### ISSUE THREAD

**Issue by javlock** [j6t/kdbg#20]
Is it possible to enter NOP (90) as an argument?

**Comment by j6t** [comment]
Without additional context, I have no idea what your question means. Can you explain what you have and what you want to do?

**Comment by javlock** [comment]
you need to pass a sequence of bytes (non-printable characters on the keyboard) as an argument

I suggest reading from a file, or executing a command and transferring the result as an argument
linux example, gdb:
gdb /usr/bin/ls

r < file.txt
r $(python2 -c 'print("A"*10 + "\x90"+120+"ADDR")')

**Comment by j6t** [comment]
There is an edit box for arguments in _Execution -> Arguments_. Can you not enter the desired text there?

If your program accepts the text on stdin, you can just put

    < file.txt

there.

**Comment by javlock** [comment]
did not work
"--help" in file /tmp/dddd
![Screenshot_20211204_160100](https://user-images.githubusercontent.com/87483305/144716221-e487737e-49db-46d1-b7c3-f0a8dcf8bce1.png)
there is output in the output window:
afl-gcc
but no afl-gcc --help

**Comment by j6t** [comment]
If you want to pass just `--help` to the program, then enter just `--help` into this edit box.

The content of this edit box is passed to GDB's `set args` command literally. The `< file.txt` that I suggested does not do anything magical. It literally only redirects the program's stdin to the file (that is how GDB works on Linux; KDbg does nothing special with it). If your program does not know what to do with the text `--help` when passed via stdin, you should not expect any magic to happen ;)

**Comment by javlock** [comment]
how do i specify specific bytes as an argument ???

**Comment by j6t** [comment]
I just entered

> $(python2 -c 'print("A"*10 + "\x90"*120+"ADDR")')

in the _Execution -> Arguments_ edit field. And it worked.

**Comment by javlock** [comment]
after 2 runs with \x90 turns into \220
lol

**Comment by javlock** [comment]
![ssss](https://user-images.githubusercontent.com/87483305/146594408-b395da09-dfc7-4fad-8013-7139da054d47.png)
