### ISSUE TITLE
[3.0.1] Shows `QCommandLineParser` errors on stderr?

### ISSUE THREAD

**Issue by hartwork** [j6t/kdbg#27]
Hi! Thanks for KDbg! :pray: 

These errors came to my attention on the terminal recently:

```console
# kdbg --version
QCommandLineParser: already having an option named "h"
QCommandLineParser: already having an option named "help-all"
QCommandLineParser: already having an option named "v"
kdbg 3.0.1

# kdbg & pid=$!; sleep 1; kill -s TERM ${pid}
QCommandLineParser: already having an option named "h"
QCommandLineParser: already having an option named "help-all"
QCommandLineParser: already having an option named "v"
```

They seem to point to a problem with use of `QCommandLineParser` inside KDbg. The way I read https://api.kde.org/frameworks/kcoreaddons/html/classKAboutData.html#afaf16b9be9deacfe10669219c50f2b43, KDbg's current call…

https://github.com/j6t/kdbg/blob/e42260448fdc884086046ea93550dfbbbc7f72df/kdbg/main.cpp#L56

…is already adding help and version for KDbg and thus making…

https://github.com/j6t/kdbg/blob/e42260448fdc884086046ea93550dfbbbc7f72df/kdbg/main.cpp#L58-L59

…cause the errors?

Thanks and best, Sebastian

PS: Qt Core is at version 5.15.10 and KCoreAddons is at 5.110.0 over here.

**Comment by hartwork** [comment]
> https://github.com/j6t/kdbg/blob/e42260448fdc884086046ea93550dfbbbc7f72df/kdbg/main.cpp#L58-L59

Dropping those two lines seems to make the errors go away while keeping `--help`, `--help-all` and `--version` working. Should I just make a pull request or does this need any version detection guards? I'm assuming there was a time without the error where these lines were needed :thinking: What do you think?

**Comment by j6t** [comment]
Nice find! It looks like `KAboutData` [handles these options](https://api.kde.org/frameworks/kcoreaddons/html/classKAboutData.html#afaf16b9be9deacfe10669219c50f2b43). It also handles `setApplicationDescription()`, which can also be removed.

The code in `KAboutData` is at least 8 years old, while these lines in KDbg are less than 7 years old. Looks like there is no versioning issue, and the code can just be removed.

**Comment by hartwork** [comment]
@j6t thanks for your quick reply! Alright, pull request upcoming…

**Comment by hartwork** [comment]
Done: #28

**Comment by j6t** [comment]
Thank you!
