### ISSUE TITLE
Contributing simple Linux CI based on GitHub Actions welcome?

### ISSUE THREAD

**Issue by hartwork** [j6t/kdbg#29]
Hi!

I noticed that this repository does not have any CI so that currently pull requests could in theory break compilation unnoticed any time even with careful review. Use of GitHub Actions would be free of cost for you, works well, and only requires addition of a single YAML file to activate. I'm thinking of an approach similar to https://github.com/projectM-visualizer/frontend-libvisual-plug-in/blob/master/.github/workflows/linux.yml , aiming to cover at least GCC 12 and Clang 17 here. What do you think? 

Best, Sebastian

**Comment by j6t** [comment]
This sounds good.

I have no experience using the build infrastructure and do not know how to read and handle build failures. One possibility to show-case this would be to build with `-Werror` because there are still some deprecation warnings during compilation. Then I could explore the CI output and ask questions what to do now.

**Comment by hartwork** [comment]
> This sounds good.

@j6t cool!

> I have no experience using the build infrastructure and do not know how to read and handle build failures. One possibility to show-case this would be to build with `-Werror` because there are still some deprecation warnings during compilation. Then I could explore the CI output and ask questions what to do now.

I noticed warnings while compiling and I was considering adding `-Werror` in a second phase while fixing all errors to make the build pass at introduction. I should add that CI should start green and stay green to be good at pointing out introduction of new breakage. How would you feel about a two-phase approach like that?

I'm not sure I fully understand what you envisioned. I'd be curious to better understand that if you have a moment to elaborate.

I'll go demo CI without `-Werror` now, with some luck I have something to show by 23:00.

**Comment by hartwork** [comment]
Done: #31
