### ISSUE TITLE
KF5-based release

### ISSUE THREAD

**Issue by a17r** [j6t/kdbg#3]
Do you have plans for a new release any time soon, or are there any known issues that potential contributors could help out with?

For context, distributions are now busy weeding out kdelibs- and even qt4- reverse-dependencies and KDE Applications 17.08.3 in ~two weeks will mark the end of official/regular kdelibs releases.

**Comment by j6t** [comment]
Thank you for pointing out the urgency to move to KF5. I'll see whether I can cut a release RSN.

**Comment by KillTheMule** [comment]
Gentoo will be removing kdbg due to this soon, see https://archives.gentoo.org/gentoo-commits/message/2dd69f443c8d5f20c57dcc1cfb1f0722.

I have no idea how much work that might be, but I can say that I like kdbg very much. Thanks for your work!

**Comment by a17r** [comment]
@KillTheMule you can test kdbg-9999:5 by adding KDE overlay for Gentoo, positive feedback may yield a snapshot in time if there is no release by then.

**Comment by KillTheMule** [comment]
Great news, thanks, I'm sure to have a look soon!

**Comment by j6t** [comment]
I have just uploaded version KDbg 3.0.0. It is based on KF5.

**Comment by a17r** [comment]
Thanks! Now available in Gentoo main ebuild repository.
