### ISSUE TITLE
Bringing back Debian/Ubuntu packages?

### ISSUE THREAD

**Issue by hartwork** [j6t/kdbg#34]
Hi @j6t,

I noticed that KDbg was removed from Debian when it was at version 2.5.5-3 [because it was using Qt4 at a time where Qt4 was on its way out](https://tracker.debian.org/news/1056739/removed-255-3-from-unstable/) and not Qt5 unlike now. While I have KDbg 3.0.1 at my fingertips in Gentoo, I personally consider it a pity that KDbg is not packaged in Debian for the masses. *If* you feel similar about it, there are at least two ways forward:

- a) Contact people from the [KDbg Debian package's past](https://metadata.ftp-master.debian.org/changelogs//main/k/kdbg/kdbg_2.5.5-3_changelog)
- b) Open a "request for packaging" (RFP) bug in Debian (— https://wnpp.debian.net/?type[]=RFP could be of interest)
- c) Make the CI produce `.deb` files (based on an adjusted version of the original past Debian 2.5.5 packaging) for download after #31 has been merged

All of these approaches have different pros and cons, e.g. (c) has the con that it teaches users that it may be okay to download and install `.deb` files while the professionally paranoid would think twice about that for good reason.

What do you think?

Best, Sebastian

**Comment by j6t** [comment]
Actually, I do not have a preference, because I do not use Debian or a derivative (yet). It is up to people who wish to have packages to help provide a suitable package source. That can be option c) if it does not amount to a maintenance nightmare.

That said, should it happen some time that I move to Debian, then I would personally have a preference for option c) because it would make me independent from other package providers.

**Comment by hartwork** [comment]
@j6t thanks for your reply! Maybe we can do all of those. I just filed an RFP request at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1055797 including original maintainers in CC so that covers (1) and (2) in some sense.
Notice that I said 3.0.2 there because 3.0.1 unpatched will be a problem to package. I'll explain that in a dedicated ticket in a minute.
For (3), with some luck that's easy and I can offer a pull request producing `.deb` files based on the original packaging before Monday. Depending how it goes, I may also need to back off, will see.

**Comment by hartwork** [comment]
> For (3), with some luck that's easy and I can offer a pull request producing `.deb` files based on the original packaging before Monday. Depending how it goes, I may also need to back off, will see.

@j6t my experiment for (c) was successful and I have pull request #37 ready now for review and testing.
