### ISSUE TITLE
Please make a release 3.0.2 with the post-3.0.1 fixes off master. Thank you!

### ISSUE THREAD

**Issue by hartwork** [j6t/kdbg#35]
Hi @j6t,

being on Gentoo I noticed that when installing package `dev-util/kdbg` in version 3.0.1 what I really get is 3.0.1 plus two patches:
- https://github.com/gentoo/gentoo/blob/master/dev-util/kdbg/files/kdbg-3.0.1-fix-rare-memleak.patch
- https://github.com/gentoo/gentoo/blob/master/dev-util/kdbg/files/kdbg-3.0.1-usable-trace.patch

Ideally a distros patch count would be at zero but these two were apparently decided to be critical enough to have to include them downstream. I'm trying to make a point here that 3.0.1 needs patches that everyone will want to have, and so a new release would help get these fixes out to users across distributions.

For me personally, I would love to see my work from #28 and #32 in a new release.

For `ReleaseNotes-3.0.2` I would like to offer this data (technically all commits that went into master directly, both regular commits and merge commits):

```console
# git log --graph --oneline | grep '^\* \|Merge branch' | head -n 27 | sed -e 's, [|/] ,  ,' -e 's, \+, ,' | tac
* d839ef6 KDbg 3.0.1.
* 0feb098 Fix a rare memory leak in the register display window
* 8f2add1 Change output for a trace so that trace is actually usable again
* c16c8aa Fix narrowing initialization of (signed) char with large, unsigned values.
* 165869f Ignore a few more files generated by cmake.
* d942812 Replace obsolete QString::sprintf by asprintf.
* 00a08bb Replace UserIcon() by KIconLoader::global()->loadIcon().
* 0524c07 Add text to the status/break ("pulse") button.
* b87324c Specify the project name as suggested by a cmake warning.
* af57946 Fix build warnings about deprecated qPixmapFromMimeSource function.
* c63bc6c Fix build warnings due to included .moc files.
* 25640f0 Merge branch 'changable-disassembly-flavor'
* bf20076 Scroll output window as new text is added.
* 474a169 Revert "Work-around for gdb 6.3 crash at info line main."
* aed8c96 Merge branch 'work/nmariusp/ctor_throws' of https://github.com/nmariusp/kdbg
* 74c2066 Merge branch 'work/nmariusp/strncmp' of https://github.com/nmariusp/kdbg
* e8f1e72 .gitignore add support for clangd, vscode, kdesrc-build
* e422604 Merge branch 'deprecated' of https://github.com/davispuh/kdbg
* a361fa3 kdbg/main.cpp: Stop adding --version, --help, --help-all twice
* eacac54 Merge branch 'https' of https://github.com/hartwork/kdbg-fork
* 1dbc782 Do not hard-code Qt5 installation paths in kdbg/testprogs/Makefile.
* d923790 Add simple CI based on GitHub Actions
* ff5021d Merge branch 'issue-5-fix-icon-installation-target' of https://github.com/hartwork/kdbg-fork
* 504b8c5 debian: Add original Debian packaging of kdbg_2.5.5-3
* | d71afc1 debian: Fix the author's email address.
* 8227b5f Merge branch 'debian-package' of https://github.com/hartwork/kdbg-fork
* 95f6eff Merge branch 'gcc-13' of https://github.com/hartwork/kdbg-fork
```
A clickable version of that would be:

* 0feb098 — Fix a rare memory leak in the register display window
* 8f2add1 — Change output for a trace so that trace is actually usable again
* c16c8aa — Fix narrowing initialization of (signed) char with large, unsigned values.
* 165869f — Ignore a few more files generated by cmake.
* d942812 — Replace obsolete `QString::sprintf` by `asprintf`.
* 00a08bb — Replace `UserIcon()` by `KIconLoader::global()->loadIcon()`.
* 0524c07 — Add text to the status/break ("pulse") button.
* b87324c — Specify the project name as suggested by a cmake warning.
* af57946 — Fix build warnings about deprecated `qPixmapFromMimeSource` function.
* c63bc6c — Fix build warnings due to included `.moc` files.
* 25640f0 — Merge branch `changable-disassembly-flavor`
* bf20076 — Scroll output window as new text is added.
* 474a169 — Revert "Work-around for gdb 6.3 crash at info line main."
* aed8c96 — Merge branch `work/nmariusp/ctor_throws` of https://github.com/nmariusp/kdbg
* 74c2066 — Merge branch `work/nmariusp/strncmp` of https://github.com/nmariusp/kdbg
* e8f1e72 — `.gitignore` add support for clangd, vscode, kdesrc-build
* e422604 — Merge branch `deprecated` of https://github.com/davispuh/kdbg
* a361fa3 — `kdbg/main.cpp`: Stop adding `--version`, `--help`, `--help-all twice`
* eacac54 — Merge branch `https` of https://github.com/hartwork/kdbg-fork
* 1dbc782 — Do not hard-code Qt5 installation paths in kdbg/testprogs/Makefile.
* d923790 — Add simple CI based on GitHub Actions
* ff5021d — Merge branch `issue-5-fix-icon-installation-target` of https://github.com/hartwork/kdbg-fork
* 504b8c5 — debian: Add original Debian packaging of kdbg_2.5.5-3
* d71afc1 — debian: Fix the author's email address.
* 8227b5f — Merge branch 'debian-package' of https://github.com/hartwork/kdbg-fork
* 95f6eff — Merge branch 'gcc-13' of https://github.com/hartwork/kdbg-fork

What do you think?

**Comment by hartwork** [comment]
@j6t FYI I have updated the raw `ReleaseNotes-3.0.2` input above for latest `master` (commit 8227b5fe1c43ec06ff8cc902c7d0d6a6260965de) now.

How do you feel about a soon KDbg 3.0.2 release? I feel it would not only help getting bugfixes to more users but also to increase our chances of getting it back into mainline Debian in time. I have two contacts I could mail about it asking who could help us there from inside Debian, and things will be significantly easier if we already have 3.0.2 we all these fixes out there before I start sending these e-mails.

**Comment by j6t** [comment]
I would plan for a 3.1 release some time soon.

**Comment by hartwork** [comment]
> I would plan for a 3.1 release some time soon.

@j6t cool! :+1: :+1:

**Comment by hartwork** [comment]
@j6t any chance to do a release 3.0.2 soon-ish and then 3.1.0 when it's ready? Are you close to completion with what you had planned? Without a release we cannot make progress downstream, with Debian in particular.

**Comment by hartwork** [comment]
@j6t that would rock

**Comment by j6t** [comment]
Please have a look at branch [master-ci-check](https://github.com/j6t/kdbg/tree/master-ci-check). I haven't updated the debian directory. Is there something to do there?

Also, I'm in the process of figuring out how to update the translations, since there are new texts to be translated.

**Comment by hartwork** [comment]
> Please have a look at branch [master-ci-check](https://github.com/j6t/kdbg/tree/master-ci-check).

@j6t could you make it a pull request up here? I could do proper line-based review supported by GitHub there, already found multiple things to adjust, e.g.:
- the change log (while a nice start!) is missing some of the bugfixes,
- contains accidental double spaces
- spelling "Github action" is wrong, "GitHub Actions" is right
- (Message "extend copyright" is somewhat misleading, because the copyright is the same, the change is cosmetic in nature.)
- (Commit dba4a75560dcbbbf5c602be272340848cf167716 could elaborate on the effect of confusing the parser, e.g. what was the user effect of this?)

> I haven't updated the debian directory. Is there something to do there?

Yes, file `debian/changelog` needs a new entry on top like this:

```
kdbg (3.1.0-1) unstable; urgency=medium

  * Release KDbg 3.1.0.

 -- Johannes Sixt <j6t@kdbg.org>  Sat, 2 Dec 2023 18:38:12 +0100
```

> Also, I'm in the process of figuring out how to update the translations, since there are new texts to be translated.

The key question is probably which languages are affected. Outside of English and German it may have to be fixed by others after the release.

**Comment by hartwork** [comment]
@j6t PS: This thing will need adjustment to the new location if we stick with moving the old release logs out of the way:

```
# git --no-pager grep ReleaseNotes debian/
debian/rules:   cat $$(ls ReleaseNotes-* | sort -Vr) ChangeLog-pre-2.2.0 | \
```

**Comment by j6t** [comment]
Thank you for the quick review!

> > Please have a look at branch [master-ci-check](https://github.com/j6t/kdbg/tree/master-ci-check).
> 
> @j6t could you make it a pull request up here? I could do proper line-based review supported by GitHub there, already found multiple things to adjust, e.g.:

No. Review in GitHub pull requests are basically unusable for me. I appreciate that you list things here, and that's just as good as if you wrote it in a review, as far as I am concerned.

> * the change log (while a nice start!) is missing some of the bugfixes,

Did I miss a *user visible* change?

> * contains accidental double spaces
> 
> * spelling "Github action" is wrong, "GitHub Actions" is right

Will fix those!

> * (Message "extend copyright" is somewhat misleading, because the copyright is the same, the change is cosmetic in nature.)

Yeah, there is some truth in your statement. However, I used this message in the past, and I'm going to use it for the same purpose now and in the future.

> * (Commit [dba4a75](https://github.com/j6t/kdbg/commit/dba4a75560dcbbbf5c602be272340848cf167716) could elaborate on the effect of confusing the parser, e.g. what was the user effect of this?)

Yes, indeed. I'm not going to change the commit, though, as it is already old. Just so you know it, the common symptom of all parser-related errors is that the list of variables is truncated.

> > I haven't updated the debian directory. Is there something to do there?
> 
> Yes, file `debian/changelog` needs a new entry on top like this:
> 
> ```
> kdbg (3.1.0-1) unstable; urgency=medium
> 
>   * Release KDbg 3.1.0.
> 
>  -- Johannes Sixt <j6t@kdbg.org>  Sat, 2 Dec 2023 18:38:12 +0100
> ```

OK, thanks. Is there a significance to the timestamp? If not, then I intend to make one up.

> 
> > Also, I'm in the process of figuring out how to update the translations, since there are new texts to be translated.
> 
> The key question is probably which languages are affected. Outside of English and German it may have to be fixed by others after the release.

It's not about getting texts translated, but how to extract the new texts from the new code.

**Comment by hartwork** [comment]
> > @j6t could you make it a pull request up here? I could do proper line-based review supported by GitHub there, already found multiple things to adjust, e.g.:
> 
> No. Review in GitHub pull requests are basically unusable for me.

@j6t okay, how so?

> I appreciate that you list things here, and that's just as good as if you wrote it in a review, as far as I am concerned.

We miss things like comments being line based, and marking things as resolved and all. The UX and value is great, if you'd ask me.

> > * the change log (while a nice start!) is missing some of the bugfixes,
> 
> Did I miss a _user visible_ change?

Yes. I did not see mentions of:

- 0feb098
- 8f2add1
- bf20076
- a361fa3

All these seem user visible and effect runtime. The first two are critical enough that distros decided to backport them onto 3.0.1. Did I overlook something?

> > * contains accidental double spaces
> > * spelling "Github action" is wrong, "GitHub Actions" is right
> 
> Will fix those!

Thanks!

For "Debian build procedure was modernized" could you make that say that we *added and* modernized it and that our source is the original packaging of `kdbg_2.5.5-3`? There was no Debian build procedure here before and we sit on their shoulders for that. Just my 2 cents.

> > * (Message "extend copyright" is somewhat misleading, because the copyright is the same, the change is cosmetic in nature.)
> 
> Yeah, there is some truth in your statement. However, I used this message in the past, and I'm going to use it for the same purpose now and in the future.

Okay, at least I tried.


> > * (Commit [dba4a75](https://github.com/j6t/kdbg/commit/dba4a75560dcbbbf5c602be272340848cf167716) could elaborate on the effect of confusing the parser, e.g. what was the user effect of this?)
> 
> Yes, indeed. I'm not going to change the commit, though, as it is already old.

Rewriting commit messages could hardly be easier with Git through `git commit --amend` and `git rebase -i <commitish>`, but okay.

> Just so you know it, the common symptom of all parser-related errors is that the list of variables is truncated.

Okay, that's a bummer. Great to have that fixed.


> > > I haven't updated the debian directory. Is there something to do there?
> > 
> > 
> > Yes, file `debian/changelog` needs a new entry on top like this:
> > ```
> > kdbg (3.1.0-1) unstable; urgency=medium
> > 
> >   * Release KDbg 3.1.0.
> > 
> >  -- Johannes Sixt <j6t@kdbg.org>  Sat, 2 Dec 2023 18:38:12 +0100
> > ```
> 
> OK, thanks. Is there a significance to the timestamp? If not, then I intend to make one up.

A made-up version close to reality would be best, at least the date should match, that would be nice.


> > > Also, I'm in the process of figuring out how to update the translations, since there are new texts to be translated.
> > 
> > 
> > The key question is probably which languages are affected. Outside of English and German it may have to be fixed by others after the release.
> 
> It's not about getting texts translated, but how to extract the new texts from the new code.

There is gettext tooling for that, haven't used it in a while myself. I can look into it if you want to pass the the token for it to me. It would end up as a pull request through :smiley:

**Comment by hartwork** [comment]
> > @j6t PS: This thing will need adjustment to the new location if we stick with moving the old release logs out of the way:
> > ```
> > # git --no-pager grep ReleaseNotes debian/
> > debian/rules:   cat $$(ls ReleaseNotes-* | sort -Vr) ChangeLog-pre-2.2.0 | \
> > ```
> 
> Good point. What's the point of this rule? And, BTW, it looks like I missed `ChangeLog-pre-2.2.0` in the commit that moves the release notes.

@j6t they concatenate all those files into a single flat file `upstream.changes` for installation, should have added `-A1` for clarity:

```
# git --no-pager grep -A1 ReleaseNotes debian/
debian/rules:   cat $$(ls ReleaseNotes-* | sort -Vr) ChangeLog-pre-2.2.0 | \
debian/rules-      egrep -av '(KDbg Release Notes for|====)' > debian/upstream.changes
```

**Comment by hartwork** [comment]
> And, BTW, it looks like I missed `ChangeLog-pre-2.2.0` in the commit that moves the release notes.

@j6t PS: Yes, nice catch! :+1:

**Comment by j6t** [comment]
> > > @j6t could you make it a pull request up here? I could do proper line-based review supported by GitHub there, already found multiple things to adjust, e.g.:
> > 
> > 
> > No. Review in GitHub pull requests are basically unusable for me.
> 
> @j6t okay, how so?
> 
> > I appreciate that you list things here, and that's just as good as if you wrote it in a review, as far as I am concerned.
> 
> We miss things like comments being line based, and marking things as resolved and all. The UX and value is great, if you'd ask me.

This didn't work at all last time I used it. Mostly because you can only comment on the total change of a PR, not on the changes of an individual commit.

> 
> > > * the change log (while a nice start!) is missing some of the bugfixes,
> > 
> > 
> > Did I miss a _user visible_ change?
> 
> Yes. I did not see mentions of:
> 
> * [0feb098](https://github.com/j6t/kdbg/commit/0feb0986f220126177084badf67813ccdbaa996c)
>
> * [8f2add1](https://github.com/j6t/kdbg/commit/8f2add1046c2d23294496bc0bc7c00d18c6aa0a2)
> 
> * [bf20076](https://github.com/j6t/kdbg/commit/bf200768dc3b1a18d60180f26bfb181bb6022276)
> 
> * [a361fa3](https://github.com/j6t/kdbg/commit/a361fa332e281f39ceea2342e346c45ffc223f94)
> 
> 
> All these seem user visible and effect runtime. The first two are critical enough that distros decided to backport them onto 3.0.1. Did I overlook something?

No, you didn't. I consider all of them either not user-visible or too minor to be mentioned.

> For "Debian build procedure was modernized" could you make that say that we _added and_ modernized it and that our source is the original packaging of `kdbg_2.5.5-3`? There was no Debian build procedure here before and we sit on their shoulders for that. Just my 2 cents.

Good point.

> > > > I haven't updated the debian directory. Is there something to do there?
> > > 
> > > 
> > > Yes, file `debian/changelog` needs a new entry on top like this:
> > > ```
> > > kdbg (3.1.0-1) unstable; urgency=medium
> > > 
> > >   * Release KDbg 3.1.0.
> > > 
> > >  -- Johannes Sixt <j6t@kdbg.org>  Sat, 2 Dec 2023 18:38:12 +0100
> > > ```
> > 
> > 
> > OK, thanks. Is there a significance to the timestamp? If not, then I intend to make one up.
> 
> A made-up version close to reality would be best, at least the date should match, that would be nice.

OK, thanks.

> > It's not about getting texts translated, but how to extract the new texts from the new code.
> 
> There is gettext tooling for that, haven't used it in a while myself. I can look into it if you want to pass the the token for it to me. It would end up as a pull request through 😃

There is already a script in the `po` directory. But it doesn't find `extractrc` on my system. Need to find that first.

**Comment by j6t** [comment]
> > Mostly because you can only comment on the total change of a PR, not on the changes of an individual commit.
> 
> @j6t you can comment on individual commits, but the comments may get lost on SHA1 change, it's not the best way on GitHub most of the time. Maybe in Gerrit. What are you used to for review?

Email (the Git and Linux kernel workflow). Or talk to the contributor in person.

> > There is already a script in the `po` directory. But it doesn't find `extractrc` on my system. Need to find that first.
> 
> I found that in kdesdk-scripts at https://packages.debian.org/search?searchon=contents&keywords=extractrc . Probably similar on SUSE.

Thanks. I'll see.

**Comment by j6t** [comment]
> @j6t there is new typo "Gitub" for "Git[H]ub" now. Other than that, things look fairly complete now, are there more things known missing?

Oops! Thanks for pointing out the mistake.

**Comment by j6t** [comment]
I have just released KDbg 3.1.0.

**Comment by hartwork** [comment]
Bumped to 3.1.0 in Gentoo myself just now: https://github.com/gentoo/gentoo/commit/5b6302044ee07040b4c3f9c183eb7e1118bb34ab .

I'm in touch with Debian, still ongoing. Here's where the other distros are at today according to [repology.org](https://repology.org/project/kdbg/versions):

![KDbg at repology](https://repology.org/badge/vertical-allrepos/kdbg.svg)

**Comment by j6t** [comment]
Thank you, that's a very useful link!
