### ISSUE TITLE
crash after startup

### ISSUE THREAD

**Issue by MauroMombelli** [j6t/kdbg#4]
```
kbuildsycoca4(966) KBuildServiceFactory::createEntry: Invalid Service :  "/home/mauro/.local/share/applications/wine-extension-jpe.desktop" 
kio_trash(969) TrashProtocol::createUDSEntry: couldn't stat  "/home/mauro/.local/share/Trash/files/esp" 
[1]    957 segmentation fault (core dumped)  kdbg
```

**Comment by j6t** [comment]
Kindly provide a backtrace, otherwise it is impossible to know where to start looking, given that there seems to be a misconfiguration at your end.

**Comment by MauroMombelli** [comment]
it is the default installation from arch linux aur, no any setup executed, it was literally the first run.

Trying with gdb, first time:

```
>gdb kdbg
Fatal Python error: Py_Initialize: Unable to get the locale encoding
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007f191f4bab80 (most recent call first):
[1]    4302 abort (core dumped)  gdb kdbg
```

started again a couple of times, i could not reproduce.

**Comment by j6t** [comment]
Hm, so you have a core file now. If it is from KDbg, you may be able to generate a backtrace. If it is from gdb, it is a gdb problem.

**Comment by j6t** [comment]
Feel free to re-open the issue when you have more details to add.
