### ISSUE TITLE
Global options sidebar entries contain space for icons despite not having any.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [j6t/kdbg#42]
Ideally, they should be dynamically resized so that there isn't a large gap beneath them:

![Screenshot_20241202_141339](https://github.com/user-attachments/assets/7a879d68-3b1f-4840-adfe-9938c09bf19d)

I presume this is an issue with Breeze itself, but I'd like to confirm before reporting it to Bugzilla.

**Comment by j6t** [comment]
What are sidebar entries?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/j6t/kdbg/issues/42#issuecomment-2512253428

@j6t, I mean the page selectors - they're labelled "Debugger" and "Miscellaneous".

**Comment by j6t** [comment]
These look like the text is centered. I don't see that there is room for an icon.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/j6t/kdbg/issues/42#issuecomment-2512891666

@j6t, I'm *not* suggesting that you add an icon, nor that the position of the text be modified. Rather, the current vertical padding beneath the label is the amount that should be present solely when an icon is. Instead, that padding should be reduced, so that the labels are more akin to entries in a `QListView`.

**Comment by j6t** [comment]
Thank you for the clarification.

Personally, I do not mind the padding. At any rate, this is not an issue with KDbg. The code uses an [unmolested `KPageDialog`](https://github.com/j6t/kdbg/blob/7b9440b7edc820f91a99d4511ed8825f9c87fd99/kdbg/dbgmainwnd.cpp#L850).

**Comment by RokeJulianLockhart** [comment]
> At any rate, this is not an issue with KDbg. The code uses an unmolested `KPageDialog`.

@j6t, thanks. That's what I expected. I'll report it upstream, to KDE.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/j6t/kdbg/issues/42#issuecomment-2514113440

@j6t, you might find https://discuss.kde.org/t/can-the-space-for-a-vertically-aligned-icon-in-kpagedialog-entires-be-removed-when-no-icons-are-present/26402/5?u=rokejulianlockhart (and the messages before it) useful.

Summarily, it does seem like KPageDialog *should* dynamically adjust to the lack of presence of iconography, but does not. However, it also appears to not be its use case.
