### ISSUE TITLE
Some action icons are missing

### ISSUE THREAD

**Issue by j6t** [j6t/kdbg#5]
The icons of the _Load Executable_ and _Set Breakpoint_ actions are missing. This happens for the KF5-based release 3.0.0.

**Comment by hartwork** [comment]
For me, it looks like this with 3.0.1 installed in practice:

![kdbg_Screenshot_20231024_224533](https://github.com/j6t/kdbg/assets/1577132/6760afac-3ebc-421e-a61e-315d38dffc42)

What I see is:
- `Load Executable` has an icon but `Set/Clear Breakpoint` does not.
- The icons that I do see are from theme [GNOME-Wine](https://github.com/gnome-colors/gnome-colors/blob/master/gnome-colors/themes/gnome-wine) not KDbg's own icons.

PS: These are the only icons named `document-open-executable` and `brkpt` and where they are installed in Gentoo:
```console
# find /usr/share/ -name document-open-executable\* 2>/dev/null | sort 
/usr/share/kdbg/icons/oxygen/16x16/actions/document-open-executable.png
/usr/share/kdbg/icons/oxygen/22x22/actions/document-open-executable.png
/usr/share/kdbg/icons/oxygen/32x32/actions/document-open-executable.png
/usr/share/kdbg/icons/oxygen/48x48/actions/document-open-executable.png
/usr/share/kdbg/icons/oxygen/scalable/actions/document-open-executable.svgz

# find /usr/share/ -name brkpt\* 2>/dev/null | sort 
/usr/share/kdbg/icons/oxygen/16x16/actions/brkpt.png
/usr/share/kdbg/icons/oxygen/22x22/actions/brkpt.png
/usr/share/kdbg/icons/oxygen/32x32/actions/brkpt.png
/usr/share/kdbg/icons/oxygen/48x48/actions/brkpt.png
/usr/share/kdbg/icons/oxygen/scalable/actions/brkpt.svgz
```

**Comment by hartwork** [comment]
PS: These are the locations that kdbg _tries_ to load icon `brkpt` from in practice:

```console
# strace -F -efile ./kdbg/kdbg |& grep icons/brkpt | grep -Eo '"[^"]+"' | sed -e "s,${USER},user123,g" -e 's/"//g' | sort -u
/etc/eselect/wine/share/icons/brkpt.png
/etc/eselect/wine/share/icons/brkpt.svg
/etc/eselect/wine/share/icons/brkpt.svgz
/etc/eselect/wine/share/icons/brkpt.xpm
/home/user123/.local/share/icons/brkpt.png
/home/user123/.local/share/icons/brkpt.svg
/home/user123/.local/share/icons/brkpt.svgz
/home/user123/.local/share/icons/brkpt.xpm
/usr/local/share/icons/brkpt.png
/usr/local/share/icons/brkpt.svg
/usr/local/share/icons/brkpt.svgz
/usr/local/share/icons/brkpt.xpm
/usr/share/icons/brkpt.png
/usr/share/icons/brkpt.svg
/usr/share/icons/brkpt.svgz
/usr/share/icons/brkpt.xpm
```

Interestingly, `/usr/share/kdbg/…` is not not tried, so that explains something.

When adding code…

```c++
KIconLoader::global()->reconfigure("", {"kdbg/icons/oxygen/scalable/actions"});
```

…to `kdbg/main.cpp`, icon `brkpt` is now found, but the fix does not seem right. @j6t any ideas how to continue from here?

**Comment by hartwork** [comment]
PS: I used something like `qInfo() << KIconLoader::global()->searchPaths();` to debug.

**Comment by hartwork** [comment]
PPS:
- `KIconLoader::addAppDir` does not seem to be an option since it [always appends `/pics`](https://api.kde.org/frameworks/kiconthemes/html/kiconloader_8cpp_source.html#l00461).
- I found that `/usr/share/kdbg/pics/` is also searched and does contain files, just not any `brkpt` ones:
  ```console
  # ls -1 /usr/share/kdbg/pics/brk*
  /usr/share/kdbg/pics/brkcond.png
  /usr/share/kdbg/pics/brkdis.png
  /usr/share/kdbg/pics/brkena.png
  /usr/share/kdbg/pics/brkorph.png
  /usr/share/kdbg/pics/brktmp.png
  ```
- `sudo cp kdbg/pics/sc-actions-brkpt.svg /usr/share/kdbg/pics/brkpt.svgz` works around the issue and makes the UI show the icon.
- A fix in that direction would be to install
  - `kdbg/pics/48-actions-brkpt.png`
  - `kdbg/pics/sc-actions-brkpt.svg`
  - `kdbg/pics/sc-actions-brkpt.svgz`
  …as `/usr/share/kdbg/pics/brkpt.(png|svg|svgz)`.
- I also noticed that the hiearchy in `/usr/share/kdbg/icons/hicolor/` is searched but the one is not `/usr/share/kdbg/icons/oxygen/`. The `oxygen/` part seems to be the problem. Once I move the oxygen icons in place temporarily a la…
  ```bash
  sudo mv -v /usr/share/kdbg/icons/oxygen/22x22/actions/* /usr/share/kdbg/icons/hicolor/22x22/actions/
  sudo rmdir /usr/share/kdbg/icons/oxygen/22x22{/actions,}
  sudo mv -v /usr/share/kdbg/icons/oxygen/* /usr/share/kdbg/icons/hicolor/
  ```
  …icon `brkpt` is found.
- So that^^ is what I think we should make the build system do at installation time (except clean of course), see pull request #32.
- I hope my little write-up was readable enough :smiley:

**Comment by j6t** [comment]
Thank you for the analysis.

I tried your patch. While it doesn't make things worse for me (I think), it does not solve all icons, either. For example, according to strace, `document-open-executable` is never searched in the `/usr/share/kdbg` hierarchy (only in `/usr/share`), but `brkpt` *is* searched (and found) in `/usr/share/kdbg`. What is going on there? The actions are set up in an identical manner, I would say. Why do they not use the same lookup strategy?

**Comment by hartwork** [comment]
@j6t PS: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup could be of interest.

**Comment by j6t** [comment]
> Just to be sure, you did do `sudo make install`, correct?

Yes!

> My understanding is that a "global theme" like GNOME-Wine for me overrides the application where possible and only icons that the theme is missing are provided by the application. That's why for me only the breakpoint icon is from kdbg while all other icons are from GNOME-Wine. I think that's a feature.

The concept is reasonable (that only missing icons are searched in the `kdbg` hierarchy). What I wanted to say is that no system theme has a `document-open-executable` icon nor a `brkpt` icon. But still, `brkpt` is found because the `kdbg` hierarchy is searched, but `document-open-executable` is not found because the `kdbg` hierarchy is *not* searched for some reason. What is the difference between the two? Why not search `kdbg` for `document-open-executable` as well?

**Comment by hartwork** [comment]
@j6t now I understand, thanks for elaborating!

Apparently the name is the problem: the hyphens are the problem. If I change `document-open-executable` to `documentopenexecutable` or `document_open_executable` then `/usr/share/kdbg/icons/hicolor/` is also searched.

**Comment by hartwork** [comment]
@j6t PS: Or it cannot start with known prefix "document-open". Only started reading https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines now …

**Comment by j6t** [comment]
It is a matter of theme fallback from a specific to a generic icon:

> The dash “-” character is used to separate levels of specificity in icon names [...] [I]f the more specific item does not exist in the current theme, and does exist in a parent theme, the generic icon from the current theme is preferred, in order to keep consistent style.

I see a generic "open document" icon instead of "open executable". So, this seems to be what happens here. The theme I use is "breeze".

**Comment by hartwork** [comment]
@j6t that makes good sense. Should I add a commit to #32 renaming the icon away from something starting with prefix `document-open-`? How would you like to continue?

**Comment by j6t** [comment]
The action is actually not a specialization of `document-open`. So, I agree it would make sense to rename it. Maybe `executable-open`?

**Comment by hartwork** [comment]
@j6t that would make it inherit from `executable` (and  `executable-open` in some sense). Is that a bug or a feature? I can rename it to what you want.

**Comment by hartwork** [comment]
@j6t done, renamed in a new commit in #5.
