### ISSUE TITLE
Warning dialog for file path

### ISSUE THREAD

**Issue by KillTheMule** [j6t/kdbg#6]
Hey!

Thanks for 3.0.0, seems to work well, apart from the missing icons (no real worry there though). Here's a small thing:

When adding arguments to the program being executed, there's a button to add a file path. When choosing a file, a warning appears that says "File exists, are you sure you want to overwrite it?" (or similar, language is german here). Selecting `yes` seems to be no problem, the path is inserted and the file left alone (at least, that was the case for me), so the warning seems unnecessary and confusing.

This is on gentoo linux. If you need more info, let me know, I'll be happy to provide it.

**Comment by j6t** [comment]
I've just pushed out a fix to the _maint_ branch.
