### ISSUE TITLE
Following source when debugging rust programs

### ISSUE THREAD

**Issue by KillTheMule** [j6t/kdbg#9]
Hi!

I've just tried debugging a rust program, and I've found a problem and have a suggestion/question.
 

1. The problem(s): ~~When loading the program, the source isn't shown. This isn't too bad, I can set a break point, and when I run the program, it stops at the breakpoint, and the source is shown. I can step through linewise, but when leaving that particular file, the window would not update, so I can't see the line I'm running anymore. I've not found a way to get that back. It works properly in the gdb TUI. I know this isn't much to go by, so my first question would be what should I investigate and what info should I provide? I'd love to debug rust programs with kdbg :)~~ This was somewhat premature, I've tried a bit, and it looks like it works, except when stepping into functions from the standardlib (maybe it's true for all dependencies, I did not get a chance to test in general).

1.  Suggestion: Can we have rust syntax highlighting?

1.  Question: Is there a way to integrate [pretty printers](https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb) in kdbg? ~~I haven't yet tried to look at variables very much, but this sounds like it would be helpfull, and maybe it's just possible already.~~ I'm not sure if that's a solution, but I can't look into parts of structs in the variable browser, maybe this prettyprinter can help :)

**Comment by j6t** [comment]
Regarding Rust syntax highlighting: It should be doable. Please open a separate issue. Maybe someone can help.

Regarding pretty printers, I've commented on issue #8.
